baseurl = "http://atokigedesu.github.io"
languageCode = "ja-jp"
title = "アトー出張所"

[params]
  description = "主にスマブラDXに関する成果物をここに置いときます。"
  twitter = "ato_ssbm"
  github = "Atokigedesu"
  mail = "refuse.reality@gmail.com"
